<?php

function form_example_menu(){
  $items = array();
  $items['examples/form_example'] = array(
    'title' => 'Example Form',
    'description' => 'A from to mess around with.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_example_form'),
    'access callback' => TRUE
  );

  return $items;
}

function form_example_form($form, &$form_state){
  $form['price'] = array(
    '#type' => 'textfield',
    '#title' => 'What is Your Price?',
    '#size' => 10,
    '#maxlength' => 10,
    '#required' => TRUE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );
  return $form;
}

function form_example_form_validate($form, &$form_state) {
  if (!($form_state['values']['price'] > 0)){
    form_set_error('price', t('Price must be a positive number.'));
  }
}

function form_example_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
}
